#Database to hold random data used to test app. Random data generated by lib/random_data.db
#(line 22) http://ruby-doc.org/core-2.1.1/Array.html#method-i-sample 

require 'random_data' #connects to random_data.rb

 # Create Posts
50.times do
 # #1
    Post.create!( #create!(bang) instructs method to throw an error if there's something wrong with the seeded data
 # #2
        title:  RandomData.random_sentence, #RandomData doesn't exist yet, "wishful coding"
        body:   RandomData.random_paragraph
    )
end
posts = Post.all
 
# Create Comments
# #3
100.times do
    Comment.create!(
 # #4
        post: posts.sample, #we call sample on the array returned by Post.all, picks a random post to associate each comment with, sample returns a random element from the array every time it's called
        body: RandomData.random_paragraph
    )
 end

 50.times do
    Advertisement.create!( 
        title: RandomData.random_sentence,
        copy: RandomData.random_paragraph,
        price: 1
        )
end

advertisements = Advertisement.all
 
 puts "Seed finished"
 puts "#{Post.count} posts created"
 puts "#{Comment.count} comments created"
 puts "#{Advertisement.count} ads created"

 #To run:
    ##rake db:seed