#Database to hold random data used to test app. Random data generated by lib/random_data.db
#(line 22) http://ruby-doc.org/core-2.1.1/Array.html#method-i-sample 
#(below line 26) https://apidock.com/rails/v4.2.1/ActiveRecord/Relation/find_or_create_by finds record with given attributes, or creates it if none are found

require 'random_data' #connects to random_data.rb

 # Create Posts
50.times do
 # #1
    Post.create!( #create!(bang) instructs method to throw an error if there's something wrong with the seeded data
 # #2
        title:  RandomData.random_sentence, #RandomData doesn't exist yet, "wishful coding"
        body:   RandomData.random_paragraph
    )
end
posts = Post.all
 
# Create Comments
# #3
100.times do
    Comment.create!(
 # #4
        post: posts.sample, #we call sample on the array returned by Post.all, picks a random post to associate each comment with, sample returns a random element from the array every time it's called
        body: RandomData.random_paragraph
    )
 end

puts"#{Post.count}"
Post.find_or_create_by(title: "This is a unique post", body:"This is the unique body")
puts"#{Post.count}"

puts"#{Comment.count}"
Comment.find_or_create_by(post: posts[posts.length - 1], body:"This is a unique comment") #will always create another as long as I'm not setting a postID, so don't worry about it making new ones right now
puts"#{Comment.count}"
 
 puts "Seed finished"
 puts "#{Post.count} posts created"
 puts "#{Comment.count} comments created"

 #To run:
    ##rake db:seed