class PostsController < ApplicationController
  def index
    @posts = Post.all #declare an instance variable @posts and assign it a collection of Post objects using the `all` method provided by ActiveRecord; `all` returns a collection of Post objects
  end

  def show
    @post = Post.find(params[:id]) #find the post that corresponds to the id in the params that was passed to show and assign it to @post. Unlike in the index method, in the show method, we populate an instance variable with a single post, rather than a collection of posts
  end

  def new
    @post = Post.new #create an instance variable, @post, then assign it an empty post returned by Post.new
  end

  def create #no view for create, works behind scenes- POST method
    # #9
        @post = Post.new #call Post.new to create new instance of Post
        @post.title = params[:post][:title]
        @post.body = params[:post][:body]
   
    # #10
        if @post.save #if post successfully saved to DB, show a success method using flash[:notice] and redirect user to route generated by @post- will take user into show view
    # #11
          flash[:notice] = "Post was saved."
          redirect_to @post
        else #if save doesn't work, flash error message and render the new view again
    # #12
          flash.now[:alert] = "There was an error saving the post. Please try again."
          render :new
        end
  end

  def edit
  end

end
